namespace ChaosMAUI.Components
{
    public partial class Styling
    {
        public class GoogleIcon
        {
            public enum Icon
            {
                _123,
                _18UpRating,
                _6FtApart,
                Abc,
                AccessibleMenu,
                AccountCircle,
                ActionKey,
                Acupuncture,
                Acute,
                Add,
                Add2,
                AddBox,
                AddCircle,
                AddReaction,
                AddTask,
                AdminMeds,
                Agender,
                AllMatch,
                Allergies,
                Allergy,
                Altitude,
                Amend,
                Apartment,
                AppBadging,
                AppRegistration,
                Apps,
                AppsOutage,
                ArrowAndEdge,
                ArrowBack,
                ArrowBack2,
                ArrowBackIos,
                ArrowBackIosNew,
                ArrowCircleDown,
                ArrowCircleLeft,
                ArrowCircleRight,
                ArrowCircleUp,
                ArrowDownward,
                ArrowDownwardAlt,
                ArrowDropDown,
                ArrowDropDownCircle,
                ArrowDropUp,
                ArrowForward,
                ArrowForwardIos,
                ArrowInsert,
                ArrowLeft,
                ArrowLeftAlt,
                ArrowMenuClose,
                ArrowMenuOpen,
                ArrowOrEdge,
                ArrowOutward,
                ArrowRange,
                ArrowRight,
                ArrowRightAlt,
                ArrowSplit,
                ArrowTopLeft,
                ArrowTopRight,
                ArrowUploadProgress,
                ArrowUploadReady,
                ArrowUpward,
                ArrowUpwardAlt,
                ArrowsInput,
                ArrowsOutput,
                ArrowsOutward,
                AssistantDirection,
                AssistantNavigation,
                Autorenew,
                BackToTab,
                Backspace,
                Badge,
                Barefoot,
                Bedtime,
                BedtimeOff,
                Blind,
                Block,
                BloodPressure,
                Bloodtype,
                BodyFat,
                BodySystem,
                Bolt,
                Bomb,
                Borg,
                BottomAppBar,
                BottomDrawer,
                BottomNavigation,
                BottomPanelClose,
                BottomPanelOpen,
                BottomRightClick,
                BottomSheets,
                Boy,
                Breastfeeding,
                Brick,
                BringYourOwnIp,
                BrowseActivity,
                BrowseGallery,
                Bubble,
                Bubbles,
                ButtonsAlt,
                Cached,
                CalendarMeal,
                CalendarMonth,
                Cancel,
                Candle,
                Cannabis,
                CaptivePortal,
                Capture,
                CardioLoad,
                Cardiology,
                Cards,
                CategorySearch,
                ChangeCircle,
                Check,
                CheckBox,
                CheckBoxOutlineBlank,
                CheckCircle,
                CheckCircleUnread,
                CheckIndeterminateSmall,
                CheckSmall,
                Cheer,
                ChefHat,
                Chess,
                ChessBishop,
                ChessBishop2,
                ChessKing,
                ChessKing2,
                ChessKnight,
                ChessPawn,
                ChessPawn2,
                ChessQueen,
                ChessRook,
                ChevronBackward,
                ChevronForward,
                ChevronLeft,
                ChevronRight,
                ChipExtraction,
                Chips,
                Chronic,
                CleanHands,
                ClearAll,
                ClearDay,
                ClinicalNotes,
                ClockArrowDown,
                ClockArrowUp,
                ClockLoader10,
                ClockLoader20,
                ClockLoader40,
                ClockLoader60,
                ClockLoader80,
                ClockLoader90,
                Close,
                CloseFullscreen,
                CloseSmall,
                Co2,
                Cognition,
                Cognition2,
                CollapseAll,
                CollapseContent,
                ComedyMask,
                ComicBubble,
                Communication,
                Communities,
                CompareArrows,
                Compost,
                Compress,
                Conditions,
                Congenital,
                ConnectWithoutContact,
                Cookie,
                CookieOff,
                Coronavirus,
                CreateNewFolder,
                Crossword,
                Crowdsource,
                Crown,
                CrueltyFree,
                Css,
                Cycle,
                Cyclone,
                DarkMode,
                DataAlert,
                DataCheck,
                DataInfoAlert,
                DataThresholding,
                Dataset,
                DatasetLinked,
                Deceased,
                Delete,
                DeleteForever,
                DeleteSweep,
                Demography,
                DensityLarge,
                DensityMedium,
                DensitySmall,
                Dentistry,
                DeployedCode,
                DeployedCodeAccount,
                DeployedCodeAlert,
                DeployedCodeHistory,
                DeployedCodeUpdate,
                Dermatology,
                Description,
                DesktopLandscape,
                DesktopLandscapeAdd,
                DesktopPortrait,
                Destruction,
                DewPoint,
                Dialogs,
                Diamond,
                DiamondShine,
                DigitalWellbeing,
                DineIn,
                DirectorySync,
                DisabledByDefault,
                Diversity1,
                Diversity2,
                Diversity3,
                Diversity4,
                DoNotDisturbOff,
                DoNotDisturbOn,
                DominoMask,
                DoneAll,
                DoneOutline,
                DoubleArrow,
                Download,
                Download2,
                DownloadDone,
                DownloadForOffline,
                Downloading,
                DragClick,
                DragIndicator,
                DragPan,
                Drone,
                Drone2,
                Dropdown,
                DynamicForm,
                Earthquake,
                Eco,
                Edit,
                EditArrowDown,
                EditArrowUp,
                EditorChoice,
                Egg,
                EggAlt,
                Eject,
                Elderly,
                ElderlyWoman,
                EmojiFoodBeverage,
                EmojiNature,
                EmojiObjects,
                EmojiPeople,
                EmojiSymbols,
                EmojiTransportation,
                Emoticon,
                EmptyDashboard,
                Enable,
                Endocrinology,
                Ent,
                ErrorMed,
                EventList,
                ExitToApp,
                Expand,
                ExpandAll,
                ExpandCircleDown,
                ExpandCircleRight,
                ExpandCircleUp,
                ExpandContent,
                ExpansionPanels,
                Explosion,
                ExtensionOff,
                Eyeglasses,
                Eyeglasses2,
                Eyeglasses2Sound,
                Face,
                Face2,
                Face3,
                Face4,
                Face5,
                Face6,
                FaceDown,
                FaceLeft,
                FaceNod,
                FaceRight,
                FaceShake,
                FaceUp,
                Falling,
                FamilyStar,
                Favorite,
                Female,
                Femur,
                FemurAlt,
                FileDownloadOff,
                FileExport,
                FileJson,
                FileOpen,
                FileUploadOff,
                FilterAlt,
                FilterAltOff,
                FilterArrowRight,
                FilterList,
                FilterListOff,
                FirstPage,
                FitScreen,
                FloatLandscape2,
                FloatPortrait2,
                Flood,
                Fluid,
                FluidBalance,
                FluidMed,
                Foggy,
                FoldedHands,
                FollowTheSigns,
                FootBones,
                Footprint,
                Forest,
                Forward,
                FrontHand,
                Fullscreen,
                FullscreenExit,
                FullscreenPortrait,
                GardenCart,
                Gastroenterology,
                Gavel,
                Genetics,
                Girl,
                GlobeBook,
                Glucose,
                GoToLine,
                Group,
                GroupAdd,
                GroupOff,
                GroupRemove,
                GroupWork,
                Groups,
                Groups2,
                Groups3,
                Guardian,
                Gynecology,
                HandBones,
                HandMeal,
                HandPackage,
                Handshake,
                HealthAndSafety,
                HealthCross,
                HeartBroken,
                HeartCheck,
                HeartMinus,
                HeartPlus,
                HeartSmile,
                Helicopter,
                Help,
                Hematology,
                Hide,
                HideSource,
                HighlightKeyboardFocus,
                HighlightMouseCursor,
                HighlightTextCursor,
                Hive,
                Hls,
                HlsOff,
                Home,
                HomeHealth,
                HourglassArrowDown,
                HourglassArrowUp,
                House,
                Html,
                Humerus,
                HumerusAlt,
                HumidityPercentage,
                IdentityPlatform,
                Iframe,
                IframeOff,
                Immunology,
                IndeterminateCheckBox,
                Info,
                Infrared,
                Inpatient,
                InputCircle,
                InstallDesktop,
                IosShare,
                Javascript,
                JumpToElement,
                Key,
                KeyOff,
                KeyVertical,
                KeyboardCommandKey,
                KeyboardControlKey,
                KeyboardDoubleArrowDown,
                KeyboardDoubleArrowLeft,
                KeyboardDoubleArrowRight,
                KeyboardDoubleArrowUp,
                KeyboardOptionKey,
                KidStar,
                LabPanel,
                LabResearch,
                Labs,
                Landslide,
                LastPage,
                LeftClick,
                LeftPanelClose,
                LeftPanelOpen,
                LibraryAdd,
                LinkedServices,
                LocalShipping,
                Login,
                Logout,
                MagnificationLarge,
                MagnificationSmall,
                Mail,
                Male,
                Man,
                Man2,
                Man3,
                Man4,
                ManageSearch,
                Manga,
                Masks,
                Massage,
                Maximize,
                MedicalInformation,
                MedicalMask,
                Medication,
                MedicationLiquid,
                Menu,
                MenuBook2,
                MenuOpen,
                Metabolism,
                Microbiology,
                MilitaryTech,
                Minimize,
                Mist,
                MixtureMed,
                Modeling,
                MonitorHeart,
                Mood,
                MoodBad,
                MoonStars,
                MoreDown,
                MoreHoriz,
                MoreUp,
                MoreVert,
                MountainFlag,
                MoveDown,
                MoveGroup,
                MoveItem,
                MoveSelectionDown,
                MoveSelectionLeft,
                MoveSelectionRight,
                MoveSelectionUp,
                MoveUp,
                MovingBeds,
                MultimodalHandEye,
                Mystery,
                Nephrology,
                Neurology,
                NewWindow,
                NoAdultContent,
                NotAccessible,
                NotAccessibleForward,
                Nutrition,
                OilBarrel,
                Oncology,
                OpenInFull,
                OpenInNew,
                OpenInNewDown,
                OpenInNewOff,
                OpenRun,
                OpenWith,
                Ophthalmology,
                OralDisease,
                Orbit,
                Orthopedics,
                OutdoorGarden,
                Outpatient,
                OutpatientMed,
                Output,
                OutputCircle,
                Owl,
                OxygenSaturation,
                PageControl,
                PageInfo,
                PartlyCloudyDay,
                PartlyCloudyNight,
                PartnerExchange,
                PartnerReports,
                PatientList,
                Pediatrics,
                Person,
                Person2,
                Person3,
                Person4,
                PersonAdd,
                PersonAlert,
                PersonApron,
                PersonCancel,
                PersonCheck,
                PersonHeart,
                PersonOff,
                PersonRaisedHand,
                PersonRemove,
                Pets,
                Php,
                Pill,
                PillOff,
                PinDrop,
                Pinch,
                Pip,
                PipExit,
                PlaceItem,
                Planet,
                PlayArrow,
                Playground,
                Playground2,
                PlayingCards,
                PointScan,
                PokerChip,
                PositionBottomLeft,
                PositionBottomRight,
                PositionTopRight,
                PottedPlant,
                PrayerTimes,
                Pregnancy,
                PregnantWoman,
                Preliminary,
                Prescriptions,
                Procedure,
                ProgressActivity,
                PromptSuggestion,
                Psychiatry,
                Psychology,
                PsychologyAlt,
                Public,
                PublicOff,
                Publish,
                Pulmonology,
                PulseAlert,
                QuestionExchange,
                QuickReference,
                QuickReferenceAll,
                Quiz,
                RadioButtonChecked,
                RadioButtonPartial,
                RadioButtonUnchecked,
                Radiology,
                Rainy,
                RainyHeavy,
                RainyLight,
                RainySnow,
                Raven,
                Rebase,
                RebaseEdit,
                RecentPatient,
                Recenter,
                Recommend,
                Recycling,
                Redo,
                ReduceCapacity,
                Refresh,
                Remove,
                RemoveDone,
                ReopenWindow,
                Repartition,
                Reply,
                ReplyAll,
                Resize,
                RespiratoryRate,
                ResponsiveLayout,
                RestartAlt,
                RestoreFromTrash,
                Rheumatology,
                RibCage,
                RightClick,
                RightPanelClose,
                RightPanelOpen,
                Ripples,
                Rocket,
                RocketLaunch,
                RotateAuto,
                Routine,
                RuleSettings,
                SafetyDivider,
                Salinity,
                Sanitizer,
                Save,
                SavedSearch,
                Schedule,
                School,
                Search,
                SearchCheck,
                SearchCheck2,
                SearchOff,
                SelectAll,
                SelectCheckBox,
                SendTimeExtension,
                SentimentCalm,
                SentimentContent,
                SentimentDissatisfied,
                SentimentExcited,
                SentimentExtremelyDissatisfied,
                SentimentFrustrated,
                SentimentNeutral,
                SentimentSad,
                SentimentSatisfied,
                SentimentStressed,
                SentimentVeryDissatisfied,
                SentimentVerySatisfied,
                SentimentWorried,
                Settings,
                SettingsAccessibility,
                SettingsApplications,
                SettingsBackupRestore,
                SettingsHeart,
                SevereCold,
                Share,
                ShareOff,
                ShareReviews,
                ShareWindows,
                ShelfAutoHide,
                ShelfPosition,
                ShieldWatch,
                ShoppingCart,
                ShoppingCartCheckout,
                ShortStay,
                Sick,
                SideNavigation,
                SignLanguage,
                SignLanguage2,
                Simulation,
                Siren,
                SirenCheck,
                SirenOpen,
                SirenQuestion,
                Skeleton,
                Skull,
                SkullList,
                Sliders,
                Snowing,
                SnowingHeavy,
                SocialDistance,
                SocialLeaderboard,
                SolarPower,
                Sort,
                SortByAlpha,
                SouthAmerica,
                SpecificGravity,
                SplitscreenLandscape,
                SplitscreenPortrait,
                SquareDot,
                Stack,
                StackGroup,
                StackOff,
                StackStar,
                Stacks,
                StadiaController,
                Star,
                StarHalf,
                StarRate,
                StarRateHalf,
                StarShine,
                Stars2,
                Start,
                Stat0,
                Stat1,
                Stat2,
                Stat3,
                StatMinus1,
                StatMinus2,
                StatMinus3,
                Step,
                StepInto,
                StepOut,
                StepOver,
                Steppers,
                Stethoscope,
                StethoscopeArrow,
                StethoscopeCheck,
                Strategy,
                SubdirectoryArrowLeft,
                SubdirectoryArrowRight,
                Subheader,
                Sunny,
                SunnySnowing,
                SupportAgent,
                Surgical,
                SwapHoriz,
                SwapHorizontalCircle,
                SwapVert,
                SwapVerticalCircle,
                Sweep,
                SwipeDown,
                SwipeDownAlt,
                SwipeLeft,
                SwipeLeftAlt,
                SwipeRight,
                SwipeRightAlt,
                SwipeUp,
                SwipeUpAlt,
                SwipeVertical,
                SwitchAccess,
                SwitchAccess2,
                SwitchAccess3,
                SwitchAccessShortcut,
                SwitchAccessShortcutAdd,
                SwitchLeft,
                SwitchRight,
                Switches,
                SwordRose,
                Symptoms,
                Sync,
                SyncAlt,
                SyncArrowDown,
                SyncArrowUp,
                SyncDesktop,
                SyncDisabled,
                SyncProblem,
                SyncSavedLocally,
                SyncSavedLocallyOff,
                Syringe,
                SystemUpdateAlt,
                Tab,
                TabClose,
                TabCloseInactive,
                TabCloseRight,
                TabDuplicate,
                TabGroup,
                TabInactive,
                TabMove,
                TabNewRight,
                TabRecent,
                TabSearch,
                TabUnselected,
                Tabs,
                Tactic,
                Taunt,
                Terminal,
                ThermostatArrowDown,
                ThermostatArrowUp,
                ThumbDown,
                ThumbUp,
                ThumbsUpDown,
                Thunderstorm,
                Tibia,
                TibiaAlt,
                TileLarge,
                TileMedium,
                TileSmall,
                TimerArrowDown,
                TimerArrowUp,
                Toast,
                ToggleOff,
                ToggleOn,
                Token,
                Toolbar,
                Tornado,
                TotalDissolvedSolids,
                Transcribe,
                Transgender,
                TravelExplore,
                Tsunami,
                UlnaRadius,
                UlnaRadiusAlt,
                Undo,
                UnfoldLess,
                UnfoldLessDouble,
                UnfoldMore,
                UnfoldMoreDouble,
                Unknown5,
                UnknownMed,
                Upload,
                Upload2,
                Urology,
                Vaccines,
                VapeFree,
                VapingRooms,
                ViewApps,
                ViewComfyAlt,
                ViewCompactAlt,
                ViewCozy,
                ViewKanban,
                ViewTimeline,
                Visibility,
                VitalSigns,
                Volcano,
                Ward,
                Warning,
                WaterBottle,
                WaterBottleLarge,
                WaterDo,
                WaterDrop,
                WaterEc,
                WaterLux,
                WaterOrp,
                WaterPh,
                WaterVoc,
                WavingHand,
                Wc,
                WeatherHail,
                WeatherMix,
                Weight,
                Whatshot,
                WidgetMedium,
                WidgetSmall,
                WidgetWidth,
                WidthFull,
                WidthNormal,
                WidthWide,
                WindPower,
                Woman,
                Woman2,
                WorkspacePremium,
                Workspaces,
                WoundsInjuries,
                Wrist,
                YoutubeSearchedFor,
                ZoomIn,
                ZoomOut
            }

            public static Dictionary<Icon, string> IconMaterialNames = new()
            {
                { Icon._123, "123" },
                { Icon._18UpRating, "18_up_rating" },
                { Icon._6FtApart, "6_ft_apart" },
                { Icon.Abc, "abc" },
                { Icon.AccessibleMenu, "accessible_menu" },
                { Icon.AccountCircle, "account_circle" },
                { Icon.ActionKey, "action_key" },
                { Icon.Acupuncture, "acupuncture" },
                { Icon.Acute, "acute" },
                { Icon.Add, "add" },
                { Icon.Add2, "add_2" },
                { Icon.AddBox, "add_box" },
                { Icon.AddCircle, "add_circle" },
                { Icon.AddReaction, "add_reaction" },
                { Icon.AddTask, "add_task" },
                { Icon.AdminMeds, "admin_meds" },
                { Icon.Agender, "agender" },
                { Icon.AllMatch, "all_match" },
                { Icon.Allergies, "allergies" },
                { Icon.Allergy, "allergy" },
                { Icon.Altitude, "altitude" },
                { Icon.Amend, "amend" },
                { Icon.Apartment, "apartment" },
                { Icon.AppBadging, "app_badging" },
                { Icon.AppRegistration, "app_registration" },
                { Icon.Apps, "apps" },
                { Icon.AppsOutage, "apps_outage" },
                { Icon.ArrowAndEdge, "arrow_and_edge" },
                { Icon.ArrowBack, "arrow_back" },
                { Icon.ArrowBack2, "arrow_back_2" },
                { Icon.ArrowBackIos, "arrow_back_ios" },
                { Icon.ArrowBackIosNew, "arrow_back_ios_new" },
                { Icon.ArrowCircleDown, "arrow_circle_down" },
                { Icon.ArrowCircleLeft, "arrow_circle_left" },
                { Icon.ArrowCircleRight, "arrow_circle_right" },
                { Icon.ArrowCircleUp, "arrow_circle_up" },
                { Icon.ArrowDownward, "arrow_downward" },
                { Icon.ArrowDownwardAlt, "arrow_downward_alt" },
                { Icon.ArrowDropDown, "arrow_drop_down" },
                { Icon.ArrowDropDownCircle, "arrow_drop_down_circle" },
                { Icon.ArrowDropUp, "arrow_drop_up" },
                { Icon.ArrowForward, "arrow_forward" },
                { Icon.ArrowForwardIos, "arrow_forward_ios" },
                { Icon.ArrowInsert, "arrow_insert" },
                { Icon.ArrowLeft, "arrow_left" },
                { Icon.ArrowLeftAlt, "arrow_left_alt" },
                { Icon.ArrowMenuClose, "arrow_menu_close" },
                { Icon.ArrowMenuOpen, "arrow_menu_open" },
                { Icon.ArrowOrEdge, "arrow_or_edge" },
                { Icon.ArrowOutward, "arrow_outward" },
                { Icon.ArrowRange, "arrow_range" },
                { Icon.ArrowRight, "arrow_right" },
                { Icon.ArrowRightAlt, "arrow_right_alt" },
                { Icon.ArrowSplit, "arrow_split" },
                { Icon.ArrowTopLeft, "arrow_top_left" },
                { Icon.ArrowTopRight, "arrow_top_right" },
                { Icon.ArrowUploadProgress, "arrow_upload_progress" },
                { Icon.ArrowUploadReady, "arrow_upload_ready" },
                { Icon.ArrowUpward, "arrow_upward" },
                { Icon.ArrowUpwardAlt, "arrow_upward_alt" },
                { Icon.ArrowsInput, "arrows_input" },
                { Icon.ArrowsOutput, "arrows_output" },
                { Icon.ArrowsOutward, "arrows_outward" },
                { Icon.AssistantDirection, "assistant_direction" },
                { Icon.AssistantNavigation, "assistant_navigation" },
                { Icon.Autorenew, "autorenew" },
                { Icon.BackToTab, "back_to_tab" },
                { Icon.Backspace, "backspace" },
                { Icon.Badge, "badge" },
                { Icon.Barefoot, "barefoot" },
                { Icon.Bedtime, "bedtime" },
                { Icon.BedtimeOff, "bedtime_off" },
                { Icon.Blind, "blind" },
                { Icon.Block, "block" },
                { Icon.BloodPressure, "blood_pressure" },
                { Icon.Bloodtype, "bloodtype" },
                { Icon.BodyFat, "body_fat" },
                { Icon.BodySystem, "body_system" },
                { Icon.Bolt, "bolt" },
                { Icon.Bomb, "bomb" },
                { Icon.Borg, "borg" },
                { Icon.BottomAppBar, "bottom_app_bar" },
                { Icon.BottomDrawer, "bottom_drawer" },
                { Icon.BottomNavigation, "bottom_navigation" },
                { Icon.BottomPanelClose, "bottom_panel_close" },
                { Icon.BottomPanelOpen, "bottom_panel_open" },
                { Icon.BottomRightClick, "bottom_right_click" },
                { Icon.BottomSheets, "bottom_sheets" },
                { Icon.Boy, "boy" },
                { Icon.Breastfeeding, "breastfeeding" },
                { Icon.Brick, "brick" },
                { Icon.BringYourOwnIp, "bring_your_own_ip" },
                { Icon.BrowseActivity, "browse_activity" },
                { Icon.BrowseGallery, "browse_gallery" },
                { Icon.Bubble, "bubble" },
                { Icon.Bubbles, "bubbles" },
                { Icon.ButtonsAlt, "buttons_alt" },
                { Icon.Cached, "cached" },
                { Icon.CalendarMeal, "calendar_meal" },
                { Icon.CalendarMonth, "calendar_month" },
                { Icon.Cancel, "cancel" },
                { Icon.Candle, "candle" },
                { Icon.Cannabis, "cannabis" },
                { Icon.CaptivePortal, "captive_portal" },
                { Icon.Capture, "capture" },
                { Icon.CardioLoad, "cardio_load" },
                { Icon.Cardiology, "cardiology" },
                { Icon.Cards, "cards" },
                { Icon.CategorySearch, "category_search" },
                { Icon.ChangeCircle, "change_circle" },
                { Icon.Check, "check" },
                { Icon.CheckBox, "check_box" },
                { Icon.CheckBoxOutlineBlank, "check_box_outline_blank" },
                { Icon.CheckCircle, "check_circle" },
                { Icon.CheckCircleUnread, "check_circle_unread" },
                { Icon.CheckIndeterminateSmall, "check_indeterminate_small" },
                { Icon.CheckSmall, "check_small" },
                { Icon.Cheer, "cheer" },
                { Icon.ChefHat, "chef_hat" },
                { Icon.Chess, "chess" },
                { Icon.ChessBishop, "chess_bishop" },
                { Icon.ChessBishop2, "chess_bishop_2" },
                { Icon.ChessKing, "chess_king" },
                { Icon.ChessKing2, "chess_king_2" },
                { Icon.ChessKnight, "chess_knight" },
                { Icon.ChessPawn, "chess_pawn" },
                { Icon.ChessPawn2, "chess_pawn_2" },
                { Icon.ChessQueen, "chess_queen" },
                { Icon.ChessRook, "chess_rook" },
                { Icon.ChevronBackward, "chevron_backward" },
                { Icon.ChevronForward, "chevron_forward" },
                { Icon.ChevronLeft, "chevron_left" },
                { Icon.ChevronRight, "chevron_right" },
                { Icon.ChipExtraction, "chip_extraction" },
                { Icon.Chips, "chips" },
                { Icon.Chronic, "chronic" },
                { Icon.CleanHands, "clean_hands" },
                { Icon.ClearAll, "clear_all" },
                { Icon.ClearDay, "clear_day" },
                { Icon.ClinicalNotes, "clinical_notes" },
                { Icon.ClockArrowDown, "clock_arrow_down" },
                { Icon.ClockArrowUp, "clock_arrow_up" },
                { Icon.ClockLoader10, "clock_loader_10" },
                { Icon.ClockLoader20, "clock_loader_20" },
                { Icon.ClockLoader40, "clock_loader_40" },
                { Icon.ClockLoader60, "clock_loader_60" },
                { Icon.ClockLoader80, "clock_loader_80" },
                { Icon.ClockLoader90, "clock_loader_90" },
                { Icon.Close, "close" },
                { Icon.CloseFullscreen, "close_fullscreen" },
                { Icon.CloseSmall, "close_small" },
                { Icon.Co2, "co2" },
                { Icon.Cognition, "cognition" },
                { Icon.Cognition2, "cognition_2" },
                { Icon.CollapseAll, "collapse_all" },
                { Icon.CollapseContent, "collapse_content" },
                { Icon.ComedyMask, "comedy_mask" },
                { Icon.ComicBubble, "comic_bubble" },
                { Icon.Communication, "communication" },
                { Icon.Communities, "communities" },
                { Icon.CompareArrows, "compare_arrows" },
                { Icon.Compost, "compost" },
                { Icon.Compress, "compress" },
                { Icon.Conditions, "conditions" },
                { Icon.Congenital, "congenital" },
                { Icon.ConnectWithoutContact, "connect_without_contact" },
                { Icon.Cookie, "cookie" },
                { Icon.CookieOff, "cookie_off" },
                { Icon.Coronavirus, "coronavirus" },
                { Icon.CreateNewFolder, "create_new_folder" },
                { Icon.Crossword, "crossword" },
                { Icon.Crowdsource, "crowdsource" },
                { Icon.Crown, "crown" },
                { Icon.CrueltyFree, "cruelty_free" },
                { Icon.Css, "css" },
                { Icon.Cycle, "cycle" },
                { Icon.Cyclone, "cyclone" },
                { Icon.DarkMode, "dark_mode" },
                { Icon.DataAlert, "data_alert" },
                { Icon.DataCheck, "data_check" },
                { Icon.DataInfoAlert, "data_info_alert" },
                { Icon.DataThresholding, "data_thresholding" },
                { Icon.Dataset, "dataset" },
                { Icon.DatasetLinked, "dataset_linked" },
                { Icon.Deceased, "deceased" },
                { Icon.Delete, "delete" },
                { Icon.DeleteForever, "delete_forever" },
                { Icon.DeleteSweep, "delete_sweep" },
                { Icon.Demography, "demography" },
                { Icon.DensityLarge, "density_large" },
                { Icon.DensityMedium, "density_medium" },
                { Icon.DensitySmall, "density_small" },
                { Icon.Dentistry, "dentistry" },
                { Icon.DeployedCode, "deployed_code" },
                { Icon.DeployedCodeAccount, "deployed_code_account" },
                { Icon.DeployedCodeAlert, "deployed_code_alert" },
                { Icon.DeployedCodeHistory, "deployed_code_history" },
                { Icon.DeployedCodeUpdate, "deployed_code_update" },
                { Icon.Dermatology, "dermatology" },
                { Icon.Description, "description" },
                { Icon.DesktopLandscape, "desktop_landscape" },
                { Icon.DesktopLandscapeAdd, "desktop_landscape_add" },
                { Icon.DesktopPortrait, "desktop_portrait" },
                { Icon.Destruction, "destruction" },
                { Icon.DewPoint, "dew_point" },
                { Icon.Dialogs, "dialogs" },
                { Icon.Diamond, "diamond" },
                { Icon.DiamondShine, "diamond_shine" },
                { Icon.DigitalWellbeing, "digital_wellbeing" },
                { Icon.DineIn, "dine_in" },
                { Icon.DirectorySync, "directory_sync" },
                { Icon.DisabledByDefault, "disabled_by_default" },
                { Icon.Diversity1, "diversity_1" },
                { Icon.Diversity2, "diversity_2" },
                { Icon.Diversity3, "diversity_3" },
                { Icon.Diversity4, "diversity_4" },
                { Icon.DoNotDisturbOff, "do_not_disturb_off" },
                { Icon.DoNotDisturbOn, "do_not_disturb_on" },
                { Icon.DominoMask, "domino_mask" },
                { Icon.DoneAll, "done_all" },
                { Icon.DoneOutline, "done_outline" },
                { Icon.DoubleArrow, "double_arrow" },
                { Icon.Download, "download" },
                { Icon.Download2, "download_2" },
                { Icon.DownloadDone, "download_done" },
                { Icon.DownloadForOffline, "download_for_offline" },
                { Icon.Downloading, "downloading" },
                { Icon.DragClick, "drag_click" },
                { Icon.DragIndicator, "drag_indicator" },
                { Icon.DragPan, "drag_pan" },
                { Icon.Drone, "drone" },
                { Icon.Drone2, "drone_2" },
                { Icon.Dropdown, "dropdown" },
                { Icon.DynamicForm, "dynamic_form" },
                { Icon.Earthquake, "earthquake" },
                { Icon.Eco, "eco" },
                { Icon.Edit, "edit" },
                { Icon.EditArrowDown, "edit_arrow_down" },
                { Icon.EditArrowUp, "edit_arrow_up" },
                { Icon.EditorChoice, "editor_choice" },
                { Icon.Egg, "egg" },
                { Icon.EggAlt, "egg_alt" },
                { Icon.Eject, "eject" },
                { Icon.Elderly, "elderly" },
                { Icon.ElderlyWoman, "elderly_woman" },
                { Icon.EmojiFoodBeverage, "emoji_food_beverage" },
                { Icon.EmojiNature, "emoji_nature" },
                { Icon.EmojiObjects, "emoji_objects" },
                { Icon.EmojiPeople, "emoji_people" },
                { Icon.EmojiSymbols, "emoji_symbols" },
                { Icon.EmojiTransportation, "emoji_transportation" },
                { Icon.Emoticon, "emoticon" },
                { Icon.EmptyDashboard, "empty_dashboard" },
                { Icon.Enable, "enable" },
                { Icon.Endocrinology, "endocrinology" },
                { Icon.Ent, "ent" },
                { Icon.ErrorMed, "error_med" },
                { Icon.EventList, "event_list" },
                { Icon.ExitToApp, "exit_to_app" },
                { Icon.Expand, "expand" },
                { Icon.ExpandAll, "expand_all" },
                { Icon.ExpandCircleDown, "expand_circle_down" },
                { Icon.ExpandCircleRight, "expand_circle_right" },
                { Icon.ExpandCircleUp, "expand_circle_up" },
                { Icon.ExpandContent, "expand_content" },
                { Icon.ExpansionPanels, "expansion_panels" },
                { Icon.Explosion, "explosion" },
                { Icon.ExtensionOff, "extension_off" },
                { Icon.Eyeglasses, "eyeglasses" },
                { Icon.Eyeglasses2, "eyeglasses_2" },
                { Icon.Eyeglasses2Sound, "eyeglasses_2_sound" },
                { Icon.Face, "face" },
                { Icon.Face2, "face_2" },
                { Icon.Face3, "face_3" },
                { Icon.Face4, "face_4" },
                { Icon.Face5, "face_5" },
                { Icon.Face6, "face_6" },
                { Icon.FaceDown, "face_down" },
                { Icon.FaceLeft, "face_left" },
                { Icon.FaceNod, "face_nod" },
                { Icon.FaceRight, "face_right" },
                { Icon.FaceShake, "face_shake" },
                { Icon.FaceUp, "face_up" },
                { Icon.Falling, "falling" },
                { Icon.FamilyStar, "family_star" },
                { Icon.Favorite, "favorite" },
                { Icon.Female, "female" },
                { Icon.Femur, "femur" },
                { Icon.FemurAlt, "femur_alt" },
                { Icon.FileDownloadOff, "file_download_off" },
                { Icon.FileExport, "file_export" },
                { Icon.FileJson, "file_json" },
                { Icon.FileOpen, "file_open" },
                { Icon.FileUploadOff, "file_upload_off" },
                { Icon.FilterAlt, "filter_alt" },
                { Icon.FilterAltOff, "filter_alt_off" },
                { Icon.FilterArrowRight, "filter_arrow_right" },
                { Icon.FilterList, "filter_list" },
                { Icon.FilterListOff, "filter_list_off" },
                { Icon.FirstPage, "first_page" },
                { Icon.FitScreen, "fit_screen" },
                { Icon.FloatLandscape2, "float_landscape_2" },
                { Icon.FloatPortrait2, "float_portrait_2" },
                { Icon.Flood, "flood" },
                { Icon.Fluid, "fluid" },
                { Icon.FluidBalance, "fluid_balance" },
                { Icon.FluidMed, "fluid_med" },
                { Icon.Foggy, "foggy" },
                { Icon.FoldedHands, "folded_hands" },
                { Icon.FollowTheSigns, "follow_the_signs" },
                { Icon.FootBones, "foot_bones" },
                { Icon.Footprint, "footprint" },
                { Icon.Forest, "forest" },
                { Icon.Forward, "forward" },
                { Icon.FrontHand, "front_hand" },
                { Icon.Fullscreen, "fullscreen" },
                { Icon.FullscreenExit, "fullscreen_exit" },
                { Icon.FullscreenPortrait, "fullscreen_portrait" },
                { Icon.GardenCart, "garden_cart" },
                { Icon.Gastroenterology, "gastroenterology" },
                { Icon.Gavel, "gavel" },
                { Icon.Genetics, "genetics" },
                { Icon.Girl, "girl" },
                { Icon.GlobeBook, "globe_book" },
                { Icon.Glucose, "glucose" },
                { Icon.GoToLine, "go_to_line" },
                { Icon.Group, "group" },
                { Icon.GroupAdd, "group_add" },
                { Icon.GroupOff, "group_off" },
                { Icon.GroupRemove, "group_remove" },
                { Icon.GroupWork, "group_work" },
                { Icon.Groups, "groups" },
                { Icon.Groups2, "groups_2" },
                { Icon.Groups3, "groups_3" },
                { Icon.Guardian, "guardian" },
                { Icon.Gynecology, "gynecology" },
                { Icon.HandBones, "hand_bones" },
                { Icon.HandMeal, "hand_meal" },
                { Icon.HandPackage, "hand_package" },
                { Icon.Handshake, "handshake" },
                { Icon.HealthAndSafety, "health_and_safety" },
                { Icon.HealthCross, "health_cross" },
                { Icon.HeartBroken, "heart_broken" },
                { Icon.HeartCheck, "heart_check" },
                { Icon.HeartMinus, "heart_minus" },
                { Icon.HeartPlus, "heart_plus" },
                { Icon.HeartSmile, "heart_smile" },
                { Icon.Helicopter, "helicopter" },
                { Icon.Help, "help" },
                { Icon.Hematology, "hematology" },
                { Icon.Hide, "hide" },
                { Icon.HideSource, "hide_source" },
                { Icon.HighlightKeyboardFocus, "highlight_keyboard_focus" },
                { Icon.HighlightMouseCursor, "highlight_mouse_cursor" },
                { Icon.HighlightTextCursor, "highlight_text_cursor" },
                { Icon.Hive, "hive" },
                { Icon.Hls, "hls" },
                { Icon.HlsOff, "hls_off" },
                { Icon.Home, "home" },
                { Icon.HomeHealth, "home_health" },
                { Icon.HourglassArrowDown, "hourglass_arrow_down" },
                { Icon.HourglassArrowUp, "hourglass_arrow_up" },
                { Icon.House, "house" },
                { Icon.Html, "html" },
                { Icon.Humerus, "humerus" },
                { Icon.HumerusAlt, "humerus_alt" },
                { Icon.HumidityPercentage, "humidity_percentage" },
                { Icon.IdentityPlatform, "identity_platform" },
                { Icon.Iframe, "iframe" },
                { Icon.IframeOff, "iframe_off" },
                { Icon.Immunology, "immunology" },
                { Icon.IndeterminateCheckBox, "indeterminate_check_box" },
                { Icon.Info, "info" },
                { Icon.Infrared, "infrared" },
                { Icon.Inpatient, "inpatient" },
                { Icon.InputCircle, "input_circle" },
                { Icon.InstallDesktop, "install_desktop" },
                { Icon.IosShare, "ios_share" },
                { Icon.Javascript, "javascript" },
                { Icon.JumpToElement, "jump_to_element" },
                { Icon.Key, "key" },
                { Icon.KeyOff, "key_off" },
                { Icon.KeyVertical, "key_vertical" },
                { Icon.KeyboardCommandKey, "keyboard_command_key" },
                { Icon.KeyboardControlKey, "keyboard_control_key" },
                { Icon.KeyboardDoubleArrowDown, "keyboard_double_arrow_down" },
                { Icon.KeyboardDoubleArrowLeft, "keyboard_double_arrow_left" },
                { Icon.KeyboardDoubleArrowRight, "keyboard_double_arrow_right" },
                { Icon.KeyboardDoubleArrowUp, "keyboard_double_arrow_up" },
                { Icon.KeyboardOptionKey, "keyboard_option_key" },
                { Icon.KidStar, "kid_star" },
                { Icon.LabPanel, "lab_panel" },
                { Icon.LabResearch, "lab_research" },
                { Icon.Labs, "labs" },
                { Icon.Landslide, "landslide" },
                { Icon.LastPage, "last_page" },
                { Icon.LeftClick, "left_click" },
                { Icon.LeftPanelClose, "left_panel_close" },
                { Icon.LeftPanelOpen, "left_panel_open" },
                { Icon.LibraryAdd, "library_add" },
                { Icon.LinkedServices, "linked_services" },
                { Icon.LocalShipping, "local_shipping" },
                { Icon.Login, "login" },
                { Icon.Logout, "logout" },
                { Icon.MagnificationLarge, "magnification_large" },
                { Icon.MagnificationSmall, "magnification_small" },
                { Icon.Mail, "mail" },
                { Icon.Male, "male" },
                { Icon.Man, "man" },
                { Icon.Man2, "man_2" },
                { Icon.Man3, "man_3" },
                { Icon.Man4, "man_4" },
                { Icon.ManageSearch, "manage_search" },
                { Icon.Manga, "manga" },
                { Icon.Masks, "masks" },
                { Icon.Massage, "massage" },
                { Icon.Maximize, "maximize" },
                { Icon.MedicalInformation, "medical_information" },
                { Icon.MedicalMask, "medical_mask" },
                { Icon.Medication, "medication" },
                { Icon.MedicationLiquid, "medication_liquid" },
                { Icon.Menu, "menu" },
                { Icon.MenuBook2, "menu_book_2" },
                { Icon.MenuOpen, "menu_open" },
                { Icon.Metabolism, "metabolism" },
                { Icon.Microbiology, "microbiology" },
                { Icon.MilitaryTech, "military_tech" },
                { Icon.Minimize, "minimize" },
                { Icon.Mist, "mist" },
                { Icon.MixtureMed, "mixture_med" },
                { Icon.Modeling, "modeling" },
                { Icon.MonitorHeart, "monitor_heart" },
                { Icon.Mood, "mood" },
                { Icon.MoodBad, "mood_bad" },
                { Icon.MoonStars, "moon_stars" },
                { Icon.MoreDown, "more_down" },
                { Icon.MoreHoriz, "more_horiz" },
                { Icon.MoreUp, "more_up" },
                { Icon.MoreVert, "more_vert" },
                { Icon.MountainFlag, "mountain_flag" },
                { Icon.MoveDown, "move_down" },
                { Icon.MoveGroup, "move_group" },
                { Icon.MoveItem, "move_item" },
                { Icon.MoveSelectionDown, "move_selection_down" },
                { Icon.MoveSelectionLeft, "move_selection_left" },
                { Icon.MoveSelectionRight, "move_selection_right" },
                { Icon.MoveSelectionUp, "move_selection_up" },
                { Icon.MoveUp, "move_up" },
                { Icon.MovingBeds, "moving_beds" },
                { Icon.MultimodalHandEye, "multimodal_hand_eye" },
                { Icon.Mystery, "mystery" },
                { Icon.Nephrology, "nephrology" },
                { Icon.Neurology, "neurology" },
                { Icon.NewWindow, "new_window" },
                { Icon.NoAdultContent, "no_adult_content" },
                { Icon.NotAccessible, "not_accessible" },
                { Icon.NotAccessibleForward, "not_accessible_forward" },
                { Icon.Nutrition, "nutrition" },
                { Icon.OilBarrel, "oil_barrel" },
                { Icon.Oncology, "oncology" },
                { Icon.OpenInFull, "open_in_full" },
                { Icon.OpenInNew, "open_in_new" },
                { Icon.OpenInNewDown, "open_in_new_down" },
                { Icon.OpenInNewOff, "open_in_new_off" },
                { Icon.OpenRun, "open_run" },
                { Icon.OpenWith, "open_with" },
                { Icon.Ophthalmology, "ophthalmology" },
                { Icon.OralDisease, "oral_disease" },
                { Icon.Orbit, "orbit" },
                { Icon.Orthopedics, "orthopedics" },
                { Icon.OutdoorGarden, "outdoor_garden" },
                { Icon.Outpatient, "outpatient" },
                { Icon.OutpatientMed, "outpatient_med" },
                { Icon.Output, "output" },
                { Icon.OutputCircle, "output_circle" },
                { Icon.Owl, "owl" },
                { Icon.OxygenSaturation, "oxygen_saturation" },
                { Icon.PageControl, "page_control" },
                { Icon.PageInfo, "page_info" },
                { Icon.PartlyCloudyDay, "partly_cloudy_day" },
                { Icon.PartlyCloudyNight, "partly_cloudy_night" },
                { Icon.PartnerExchange, "partner_exchange" },
                { Icon.PartnerReports, "partner_reports" },
                { Icon.PatientList, "patient_list" },
                { Icon.Pediatrics, "pediatrics" },
                { Icon.Person, "person" },
                { Icon.Person2, "person_2" },
                { Icon.Person3, "person_3" },
                { Icon.Person4, "person_4" },
                { Icon.PersonAdd, "person_add" },
                { Icon.PersonAlert, "person_alert" },
                { Icon.PersonApron, "person_apron" },
                { Icon.PersonCancel, "person_cancel" },
                { Icon.PersonCheck, "person_check" },
                { Icon.PersonHeart, "person_heart" },
                { Icon.PersonOff, "person_off" },
                { Icon.PersonRaisedHand, "person_raised_hand" },
                { Icon.PersonRemove, "person_remove" },
                { Icon.Pets, "pets" },
                { Icon.Php, "php" },
                { Icon.Pill, "pill" },
                { Icon.PillOff, "pill_off" },
                { Icon.PinDrop, "pin_drop" },
                { Icon.Pinch, "pinch" },
                { Icon.Pip, "pip" },
                { Icon.PipExit, "pip_exit" },
                { Icon.PlaceItem, "place_item" },
                { Icon.Planet, "planet" },
                { Icon.PlayArrow, "play_arrow" },
                { Icon.Playground, "playground" },
                { Icon.Playground2, "playground_2" },
                { Icon.PlayingCards, "playing_cards" },
                { Icon.PointScan, "point_scan" },
                { Icon.PokerChip, "poker_chip" },
                { Icon.PositionBottomLeft, "position_bottom_left" },
                { Icon.PositionBottomRight, "position_bottom_right" },
                { Icon.PositionTopRight, "position_top_right" },
                { Icon.PottedPlant, "potted_plant" },
                { Icon.PrayerTimes, "prayer_times" },
                { Icon.Pregnancy, "pregnancy" },
                { Icon.PregnantWoman, "pregnant_woman" },
                { Icon.Preliminary, "preliminary" },
                { Icon.Prescriptions, "prescriptions" },
                { Icon.Procedure, "procedure" },
                { Icon.ProgressActivity, "progress_activity" },
                { Icon.PromptSuggestion, "prompt_suggestion" },
                { Icon.Psychiatry, "psychiatry" },
                { Icon.Psychology, "psychology" },
                { Icon.PsychologyAlt, "psychology_alt" },
                { Icon.Public, "public" },
                { Icon.PublicOff, "public_off" },
                { Icon.Publish, "publish" },
                { Icon.Pulmonology, "pulmonology" },
                { Icon.PulseAlert, "pulse_alert" },
                { Icon.QuestionExchange, "question_exchange" },
                { Icon.QuickReference, "quick_reference" },
                { Icon.QuickReferenceAll, "quick_reference_all" },
                { Icon.Quiz, "quiz" },
                { Icon.RadioButtonChecked, "radio_button_checked" },
                { Icon.RadioButtonPartial, "radio_button_partial" },
                { Icon.RadioButtonUnchecked, "radio_button_unchecked" },
                { Icon.Radiology, "radiology" },
                { Icon.Rainy, "rainy" },
                { Icon.RainyHeavy, "rainy_heavy" },
                { Icon.RainyLight, "rainy_light" },
                { Icon.RainySnow, "rainy_snow" },
                { Icon.Raven, "raven" },
                { Icon.Rebase, "rebase" },
                { Icon.RebaseEdit, "rebase_edit" },
                { Icon.RecentPatient, "recent_patient" },
                { Icon.Recenter, "recenter" },
                { Icon.Recommend, "recommend" },
                { Icon.Recycling, "recycling" },
                { Icon.Redo, "redo" },
                { Icon.ReduceCapacity, "reduce_capacity" },
                { Icon.Refresh, "refresh" },
                { Icon.Remove, "remove" },
                { Icon.RemoveDone, "remove_done" },
                { Icon.ReopenWindow, "reopen_window" },
                { Icon.Repartition, "repartition" },
                { Icon.Reply, "reply" },
                { Icon.ReplyAll, "reply_all" },
                { Icon.Resize, "resize" },
                { Icon.RespiratoryRate, "respiratory_rate" },
                { Icon.ResponsiveLayout, "responsive_layout" },
                { Icon.RestartAlt, "restart_alt" },
                { Icon.RestoreFromTrash, "restore_from_trash" },
                { Icon.Rheumatology, "rheumatology" },
                { Icon.RibCage, "rib_cage" },
                { Icon.RightClick, "right_click" },
                { Icon.RightPanelClose, "right_panel_close" },
                { Icon.RightPanelOpen, "right_panel_open" },
                { Icon.Ripples, "ripples" },
                { Icon.Rocket, "rocket" },
                { Icon.RocketLaunch, "rocket_launch" },
                { Icon.RotateAuto, "rotate_auto" },
                { Icon.Routine, "routine" },
                { Icon.RuleSettings, "rule_settings" },
                { Icon.SafetyDivider, "safety_divider" },
                { Icon.Salinity, "salinity" },
                { Icon.Sanitizer, "sanitizer" },
                { Icon.Save, "save" },
                { Icon.SavedSearch, "saved_search" },
                { Icon.Schedule, "schedule" },
                { Icon.School, "school" },
                { Icon.Search, "search" },
                { Icon.SearchCheck, "search_check" },
                { Icon.SearchCheck2, "search_check_2" },
                { Icon.SearchOff, "search_off" },
                { Icon.SelectAll, "select_all" },
                { Icon.SelectCheckBox, "select_check_box" },
                { Icon.SendTimeExtension, "send_time_extension" },
                { Icon.SentimentCalm, "sentiment_calm" },
                { Icon.SentimentContent, "sentiment_content" },
                { Icon.SentimentDissatisfied, "sentiment_dissatisfied" },
                { Icon.SentimentExcited, "sentiment_excited" },
                { Icon.SentimentExtremelyDissatisfied, "sentiment_extremely_dissatisfied" },
                { Icon.SentimentFrustrated, "sentiment_frustrated" },
                { Icon.SentimentNeutral, "sentiment_neutral" },
                { Icon.SentimentSad, "sentiment_sad" },
                { Icon.SentimentSatisfied, "sentiment_satisfied" },
                { Icon.SentimentStressed, "sentiment_stressed" },
                { Icon.SentimentVeryDissatisfied, "sentiment_very_dissatisfied" },
                { Icon.SentimentVerySatisfied, "sentiment_very_satisfied" },
                { Icon.SentimentWorried, "sentiment_worried" },
                { Icon.Settings, "settings" },
                { Icon.SettingsAccessibility, "settings_accessibility" },
                { Icon.SettingsApplications, "settings_applications" },
                { Icon.SettingsBackupRestore, "settings_backup_restore" },
                { Icon.SettingsHeart, "settings_heart" },
                { Icon.SevereCold, "severe_cold" },
                { Icon.Share, "share" },
                { Icon.ShareOff, "share_off" },
                { Icon.ShareReviews, "share_reviews" },
                { Icon.ShareWindows, "share_windows" },
                { Icon.ShelfAutoHide, "shelf_auto_hide" },
                { Icon.ShelfPosition, "shelf_position" },
                { Icon.ShieldWatch, "shield_watch" },
                { Icon.ShoppingCart, "shopping_cart" },
                { Icon.ShoppingCartCheckout, "shopping_cart_checkout" },
                { Icon.ShortStay, "short_stay" },
                { Icon.Sick, "sick" },
                { Icon.SideNavigation, "side_navigation" },
                { Icon.SignLanguage, "sign_language" },
                { Icon.SignLanguage2, "sign_language_2" },
                { Icon.Simulation, "simulation" },
                { Icon.Siren, "siren" },
                { Icon.SirenCheck, "siren_check" },
                { Icon.SirenOpen, "siren_open" },
                { Icon.SirenQuestion, "siren_question" },
                { Icon.Skeleton, "skeleton" },
                { Icon.Skull, "skull" },
                { Icon.SkullList, "skull_list" },
                { Icon.Sliders, "sliders" },
                { Icon.Snowing, "snowing" },
                { Icon.SnowingHeavy, "snowing_heavy" },
                { Icon.SocialDistance, "social_distance" },
                { Icon.SocialLeaderboard, "social_leaderboard" },
                { Icon.SolarPower, "solar_power" },
                { Icon.Sort, "sort" },
                { Icon.SortByAlpha, "sort_by_alpha" },
                { Icon.SouthAmerica, "south_america" },
                { Icon.SpecificGravity, "specific_gravity" },
                { Icon.SplitscreenLandscape, "splitscreen_landscape" },
                { Icon.SplitscreenPortrait, "splitscreen_portrait" },
                { Icon.SquareDot, "square_dot" },
                { Icon.Stack, "stack" },
                { Icon.StackGroup, "stack_group" },
                { Icon.StackOff, "stack_off" },
                { Icon.StackStar, "stack_star" },
                { Icon.Stacks, "stacks" },
                { Icon.StadiaController, "stadia_controller" },
                { Icon.Star, "star" },
                { Icon.StarHalf, "star_half" },
                { Icon.StarRate, "star_rate" },
                { Icon.StarRateHalf, "star_rate_half" },
                { Icon.StarShine, "star_shine" },
                { Icon.Stars2, "stars_2" },
                { Icon.Start, "start" },
                { Icon.Stat0, "stat_0" },
                { Icon.Stat1, "stat_1" },
                { Icon.Stat2, "stat_2" },
                { Icon.Stat3, "stat_3" },
                { Icon.StatMinus1, "stat_minus_1" },
                { Icon.StatMinus2, "stat_minus_2" },
                { Icon.StatMinus3, "stat_minus_3" },
                { Icon.Step, "step" },
                { Icon.StepInto, "step_into" },
                { Icon.StepOut, "step_out" },
                { Icon.StepOver, "step_over" },
                { Icon.Steppers, "steppers" },
                { Icon.Stethoscope, "stethoscope" },
                { Icon.StethoscopeArrow, "stethoscope_arrow" },
                { Icon.StethoscopeCheck, "stethoscope_check" },
                { Icon.Strategy, "strategy" },
                { Icon.SubdirectoryArrowLeft, "subdirectory_arrow_left" },
                { Icon.SubdirectoryArrowRight, "subdirectory_arrow_right" },
                { Icon.Subheader, "subheader" },
                { Icon.Sunny, "sunny" },
                { Icon.SunnySnowing, "sunny_snowing" },
                { Icon.SupportAgent, "support_agent" },
                { Icon.Surgical, "surgical" },
                { Icon.SwapHoriz, "swap_horiz" },
                { Icon.SwapHorizontalCircle, "swap_horizontal_circle" },
                { Icon.SwapVert, "swap_vert" },
                { Icon.SwapVerticalCircle, "swap_vertical_circle" },
                { Icon.Sweep, "sweep" },
                { Icon.SwipeDown, "swipe_down" },
                { Icon.SwipeDownAlt, "swipe_down_alt" },
                { Icon.SwipeLeft, "swipe_left" },
                { Icon.SwipeLeftAlt, "swipe_left_alt" },
                { Icon.SwipeRight, "swipe_right" },
                { Icon.SwipeRightAlt, "swipe_right_alt" },
                { Icon.SwipeUp, "swipe_up" },
                { Icon.SwipeUpAlt, "swipe_up_alt" },
                { Icon.SwipeVertical, "swipe_vertical" },
                { Icon.SwitchAccess, "switch_access" },
                { Icon.SwitchAccess2, "switch_access_2" },
                { Icon.SwitchAccess3, "switch_access_3" },
                { Icon.SwitchAccessShortcut, "switch_access_shortcut" },
                { Icon.SwitchAccessShortcutAdd, "switch_access_shortcut_add" },
                { Icon.SwitchLeft, "switch_left" },
                { Icon.SwitchRight, "switch_right" },
                { Icon.Switches, "switches" },
                { Icon.SwordRose, "sword_rose" },
                { Icon.Symptoms, "symptoms" },
                { Icon.Sync, "sync" },
                { Icon.SyncAlt, "sync_alt" },
                { Icon.SyncArrowDown, "sync_arrow_down" },
                { Icon.SyncArrowUp, "sync_arrow_up" },
                { Icon.SyncDesktop, "sync_desktop" },
                { Icon.SyncDisabled, "sync_disabled" },
                { Icon.SyncProblem, "sync_problem" },
                { Icon.SyncSavedLocally, "sync_saved_locally" },
                { Icon.SyncSavedLocallyOff, "sync_saved_locally_off" },
                { Icon.Syringe, "syringe" },
                { Icon.SystemUpdateAlt, "system_update_alt" },
                { Icon.Tab, "tab" },
                { Icon.TabClose, "tab_close" },
                { Icon.TabCloseInactive, "tab_close_inactive" },
                { Icon.TabCloseRight, "tab_close_right" },
                { Icon.TabDuplicate, "tab_duplicate" },
                { Icon.TabGroup, "tab_group" },
                { Icon.TabInactive, "tab_inactive" },
                { Icon.TabMove, "tab_move" },
                { Icon.TabNewRight, "tab_new_right" },
                { Icon.TabRecent, "tab_recent" },
                { Icon.TabSearch, "tab_search" },
                { Icon.TabUnselected, "tab_unselected" },
                { Icon.Tabs, "tabs" },
                { Icon.Tactic, "tactic" },
                { Icon.Taunt, "taunt" },
                { Icon.Terminal, "terminal" },
                { Icon.ThermostatArrowDown, "thermostat_arrow_down" },
                { Icon.ThermostatArrowUp, "thermostat_arrow_up" },
                { Icon.ThumbDown, "thumb_down" },
                { Icon.ThumbUp, "thumb_up" },
                { Icon.ThumbsUpDown, "thumbs_up_down" },
                { Icon.Thunderstorm, "thunderstorm" },
                { Icon.Tibia, "tibia" },
                { Icon.TibiaAlt, "tibia_alt" },
                { Icon.TileLarge, "tile_large" },
                { Icon.TileMedium, "tile_medium" },
                { Icon.TileSmall, "tile_small" },
                { Icon.TimerArrowDown, "timer_arrow_down" },
                { Icon.TimerArrowUp, "timer_arrow_up" },
                { Icon.Toast, "toast" },
                { Icon.ToggleOff, "toggle_off" },
                { Icon.ToggleOn, "toggle_on" },
                { Icon.Token, "token" },
                { Icon.Toolbar, "toolbar" },
                { Icon.Tornado, "tornado" },
                { Icon.TotalDissolvedSolids, "total_dissolved_solids" },
                { Icon.Transcribe, "transcribe" },
                { Icon.Transgender, "transgender" },
                { Icon.TravelExplore, "travel_explore" },
                { Icon.Tsunami, "tsunami" },
                { Icon.UlnaRadius, "ulna_radius" },
                { Icon.UlnaRadiusAlt, "ulna_radius_alt" },
                { Icon.Undo, "undo" },
                { Icon.UnfoldLess, "unfold_less" },
                { Icon.UnfoldLessDouble, "unfold_less_double" },
                { Icon.UnfoldMore, "unfold_more" },
                { Icon.UnfoldMoreDouble, "unfold_more_double" },
                { Icon.Unknown5, "unknown_5" },
                { Icon.UnknownMed, "unknown_med" },
                { Icon.Upload, "upload" },
                { Icon.Upload2, "upload_2" },
                { Icon.Urology, "urology" },
                { Icon.Vaccines, "vaccines" },
                { Icon.VapeFree, "vape_free" },
                { Icon.VapingRooms, "vaping_rooms" },
                { Icon.ViewApps, "view_apps" },
                { Icon.ViewComfyAlt, "view_comfy_alt" },
                { Icon.ViewCompactAlt, "view_compact_alt" },
                { Icon.ViewCozy, "view_cozy" },
                { Icon.ViewKanban, "view_kanban" },
                { Icon.ViewTimeline, "view_timeline" },
                { Icon.Visibility, "visibility" },
                { Icon.VitalSigns, "vital_signs" },
                { Icon.Volcano, "volcano" },
                { Icon.Ward, "ward" },
                { Icon.Warning, "warning" },
                { Icon.WaterBottle, "water_bottle" },
                { Icon.WaterBottleLarge, "water_bottle_large" },
                { Icon.WaterDo, "water_do" },
                { Icon.WaterDrop, "water_drop" },
                { Icon.WaterEc, "water_ec" },
                { Icon.WaterLux, "water_lux" },
                { Icon.WaterOrp, "water_orp" },
                { Icon.WaterPh, "water_ph" },
                { Icon.WaterVoc, "water_voc" },
                { Icon.WavingHand, "waving_hand" },
                { Icon.Wc, "wc" },
                { Icon.WeatherHail, "weather_hail" },
                { Icon.WeatherMix, "weather_mix" },
                { Icon.Weight, "weight" },
                { Icon.Whatshot, "whatshot" },
                { Icon.WidgetMedium, "widget_medium" },
                { Icon.WidgetSmall, "widget_small" },
                { Icon.WidgetWidth, "widget_width" },
                { Icon.WidthFull, "width_full" },
                { Icon.WidthNormal, "width_normal" },
                { Icon.WidthWide, "width_wide" },
                { Icon.WindPower, "wind_power" },
                { Icon.Woman, "woman" },
                { Icon.Woman2, "woman_2" },
                { Icon.WorkspacePremium, "workspace_premium" },
                { Icon.Workspaces, "workspaces" },
                { Icon.WoundsInjuries, "wounds_injuries" },
                { Icon.Wrist, "wrist" },
                { Icon.YoutubeSearchedFor, "youtube_searched_for" },
                { Icon.ZoomIn, "zoom_in" },
                { Icon.ZoomOut, "zoom_out" }
            };
        }
    }
}